// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Bindings for libdvcore.so (Go core). Generated by ffigen - do not edit.
class DvCoreBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  DvCoreBindings(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  DvCoreBindings.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
    : _lookup = lookup;

  int DV_Cancel(int id) {
    return _DV_Cancel(id);
  }

  late final _DV_CancelPtr = _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int64)>>('DV_Cancel');
  late final _DV_Cancel = _DV_CancelPtr.asFunction<int Function(int)>();

  void DV_Detach(int id) {
    return _DV_Detach(id);
  }

  late final _DV_DetachPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>('DV_Detach');
  late final _DV_Detach = _DV_DetachPtr.asFunction<void Function(int)>();

  ffi.Pointer<ffi.Char> DV_Download(ffi.Pointer<ffi.Char> request_json, dv_event_cb cb) {
    return _DV_Download(request_json, cb);
  }

  late final _DV_DownloadPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, dv_event_cb)>>('DV_Download');
  late final _DV_Download =
      _DV_DownloadPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, dv_event_cb)>();

  void DV_Free(ffi.Pointer<ffi.Char> p) {
    return _DV_Free(p);
  }

  late final _DV_FreePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>('DV_Free');
  late final _DV_Free = _DV_FreePtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> DV_InstaParse(ffi.Pointer<ffi.Char> request_json) {
    return _DV_InstaParse(request_json);
  }

  late final _DV_InstaParsePtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>(
    'DV_InstaParse',
  );
  late final _DV_InstaParse = _DV_InstaParsePtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> DV_InstaQuery(ffi.Pointer<ffi.Char> request_json) {
    return _DV_InstaQuery(request_json);
  }

  late final _DV_InstaQueryPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>(
    'DV_InstaQuery',
  );
  late final _DV_InstaQuery = _DV_InstaQueryPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> DV_MusicLink(ffi.Pointer<ffi.Char> request_json) {
    return _DV_MusicLink(request_json);
  }

  late final _DV_MusicLinkPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>(
    'DV_MusicLink',
  );
  late final _DV_MusicLink = _DV_MusicLinkPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> DV_MusicMeta(ffi.Pointer<ffi.Char> request_json) {
    return _DV_MusicMeta(request_json);
  }

  late final _DV_MusicMetaPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>(
    'DV_MusicMeta',
  );
  late final _DV_MusicMeta = _DV_MusicMetaPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> DV_MusicPick(ffi.Pointer<ffi.Char> request_json) {
    return _DV_MusicPick(request_json);
  }

  late final _DV_MusicPickPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>(
    'DV_MusicPick',
  );
  late final _DV_MusicPick = _DV_MusicPickPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  int DV_Pause(int id) {
    return _DV_Pause(id);
  }

  late final _DV_PausePtr = _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int64)>>('DV_Pause');
  late final _DV_Pause = _DV_PausePtr.asFunction<int Function(int)>();

  ffi.Pointer<ffi.Char> DV_Ping(ffi.Pointer<ffi.Char> msg) {
    return _DV_Ping(msg);
  }

  late final _DV_PingPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>(
    'DV_Ping',
  );
  late final _DV_Ping = _DV_PingPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  void DV_PingAsync(int id, int count, dv_event_cb cb) {
    return _DV_PingAsync(id, count, cb);
  }

  late final _DV_PingAsyncPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32, dv_event_cb)>>(
    'DV_PingAsync',
  );
  late final _DV_PingAsync = _DV_PingAsyncPtr.asFunction<void Function(int, int, dv_event_cb)>();

  ffi.Pointer<ffi.Char> DV_Probe(ffi.Pointer<ffi.Char> request_json) {
    return _DV_Probe(request_json);
  }

  late final _DV_ProbePtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>(
    'DV_Probe',
  );
  late final _DV_Probe = _DV_ProbePtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  void DV_Remove(int id) {
    return _DV_Remove(id);
  }

  late final _DV_RemovePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>('DV_Remove');
  late final _DV_Remove = _DV_RemovePtr.asFunction<void Function(int)>();

  ffi.Pointer<ffi.Char> DV_Replace(ffi.Pointer<ffi.Char> request_json) {
    return _DV_Replace(request_json);
  }

  late final _DV_ReplacePtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>(
    'DV_Replace',
  );
  late final _DV_Replace = _DV_ReplacePtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  int DV_Resume(int id) {
    return _DV_Resume(id);
  }

  late final _DV_ResumePtr = _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int64)>>('DV_Resume');
  late final _DV_Resume = _DV_ResumePtr.asFunction<int Function(int)>();

  void DV_SetMaxConcurrent(int n) {
    return _DV_SetMaxConcurrent(n);
  }

  late final _DV_SetMaxConcurrentPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int32)>>('DV_SetMaxConcurrent');
  late final _DV_SetMaxConcurrent = _DV_SetMaxConcurrentPtr.asFunction<void Function(int)>();

  ffi.Pointer<ffi.Char> DV_Status() {
    return _DV_Status();
  }

  late final _DV_StatusPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>('DV_Status');
  late final _DV_Status = _DV_StatusPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> DV_ThreadsParse(ffi.Pointer<ffi.Char> request_json) {
    return _DV_ThreadsParse(request_json);
  }

  late final _DV_ThreadsParsePtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>(
    'DV_ThreadsParse',
  );
  late final _DV_ThreadsParse = _DV_ThreadsParsePtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> DV_ThreadsQuery(ffi.Pointer<ffi.Char> request_json) {
    return _DV_ThreadsQuery(request_json);
  }

  late final _DV_ThreadsQueryPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>(
    'DV_ThreadsQuery',
  );
  late final _DV_ThreadsQuery = _DV_ThreadsQueryPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> DV_Version() {
    return _DV_Version();
  }

  late final _DV_VersionPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>('DV_Version');
  late final _DV_Version = _DV_VersionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> DV_Ytdlp(ffi.Pointer<ffi.Char> request_json) {
    return _DV_Ytdlp(request_json);
  }

  late final _DV_YtdlpPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>(
    'DV_Ytdlp',
  );
  late final _DV_Ytdlp = _DV_YtdlpPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();
}

typedef dv_event_cb = ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int64 id, ffi.Pointer<ffi.Char> json)>>;
